name: lemp

services:
  mariadb:
    image: mariadb:11.2.3-jammy
    container_name: mariadb
    restart: always
    expose:
      - 3306
    volumes:
      - lemp_db_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: rds_mysql
      MARIADB_USER: wpress
      MARIADB_PASSWORD: wpress_247x
      MARIADB_ROOT_PASSWORD: root_wpress_247x
    networks:
      - nginx

  wordpress:
    depends_on:
      - mariadb
    image: wordpress:6.4.1-php8.1
    container_name: wordpress
    restart: unless-stopped
    expose:
      - 80
      - 443
    extra_hosts:
      - wordpress.local:172.17.0.1
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wpress
      WORDPRESS_DB_PASSWORD: wpress_247x
      WORDPRESS_DB_NAME: rds_mysql
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_DISPLAY', true );
        define( 'WP_DEBUG_LOG', true );
    networks:
      - nginx

  nginx:
    image: nginx:1.25.2
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/my_wpress_site.crt:/etc/nginx/my_wpress_site.crt
      - ./nginx/ssl/my_wpress_site.key:/etc/nginx/my_wpress_site.key
      - /var/log/nginx:/var/log/nginx
    networks:
      - nginx

volumes:
  lemp_db_data:
    external: true

networks:
  nginx:
    name: nginx

