services:
  db:
    image: mysql:5.7
    container_name: wp_mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: rds_mysql
      MYSQL_USER: wpress
      MYSQL_PASSWORD: wpress_247x
      MYSQL_ROOT_PASSWORD: root_wpress_247x
    networks:
      - nginx


  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wp_site
    restart: unless-stopped
    extra_hosts:
      - wordpress.localhost:172.17.0.1
    volumes:
      - wordpress:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpress
      WORDPRESS_DB_PASSWORD: wpress_247x
      WORDPRESS_DB_NAME: rds_mysql
    networks:
      - nginx

  nginx:
    image: nginx:latest
    container_name: wp_nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/my_wpress_site.crt:/etc/nginx/my_wpress_site.crt
      - ./nginx/ssl/my_wpress_site.key:/etc/nginx/my_wpress_site.key
      - /var/log/nginx:/var/log/nginx
    networks:
      - nginx

volumes:
  mysql:
    external: true
  wordpress:
    external: true

networks:
  nginx:
    name: nginx

